project:
  type: book
  output-dir: docs

book:
  title: "臨床薬理に関する解析用標準プログラムの作成"
  author: "CDISC Japan User Group/ADaM therma 6"
  date: "11/1/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - r-env.qmd
    - tidyverse.qmd
    - adnca_desc.qmd
    - adnca_flow.qmd
    - nca_desc.qmd
    - nca_flow.qmd
    - output_desc.qmd
    - output_flow.qmd
    - references.qmd
  downloads: [docx,pdf]
  
bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    toc: true
    toc-depth: 3
    number-sections: true
lang: "ja"
pdf-engine: lualatex
documentclass: ltjsarticle 
    
editor: visual

