project:
  type: book
  output-dir: docs

book:
  title: "臨床薬理に関する解析用標準プログラムの作成"
  author: "CDISC Japan User Group/ADaM therma 3"
  date: "1/11/2024"
  chapters:
    - index.qmd
    - intro.qmd
#    - r-env.qmd
#    - tidyverse.qmd
    - adnca_desc.qmd
    - adnca_flow.qmd
    - nca_desc.qmd
    - nca_flow.qmd
    - output_desc.qmd
    - output_flow.qmd
    - output_flow2.qmd
#   - output_flow2.qmd
    - references.qmd
    
bibliography: references.bib

lang: jp

format:
  html:
    theme: cosmo
  pdf:
    toc: true
    toc-depth: 3
    number-sections: true
    documentclass: scrreprt
#    include-in-header: 
#      text: |
#        \usepackage{makeidx}
#        \makeindex
#    include-after-body: 
#      text: |
#        \printindex
  docx:
    reference-doc: custom-reference.docx
    
pdf-engine: lualatex
documentclass: ltjsarticle
editor: visual
